### ISSUE TITLE
make test does not seem to run tests correctly

### ISSUE THREAD

**Issue by n00shie** [jcpetkovich/App-QuestionValidator#2]
In other words, the tests are not even running.

**Output:**

$ make test                                  [ruby-1.9.3-p194]
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ....... 1/? # Testing App::QuestionValidator 0.01, Perl 5.012004, /usr/bin/perl
t/00-load.t ....... ok  
t/invalid.t ....... # Looks like your test exited with 25 before it could output anything.
t/invalid.t ....... Dubious, test returned 25 (wstat 6400, 0x1900)
Failed 14/14 subtests 
t/manifest.t ...... skipped: Author tests not required for installation
t/pod-coverage.t .. skipped: Test::Pod::Coverage 1.08 required for testing POD coverage
t/pod.t ........... ok  
t/valid.t ......... ok     

Test Summary Report
t/invalid.t     (Wstat: 6400 Tests: 0 Failed: 0)
  Non-zero exit status: 25
  Parse errors: Bad plan.  You planned 14 tests but ran 0.
Files=6, Tests=17,  0 wallclock secs ( 0.04 usr  0.02 sys +  0.25 cusr  0.04 csys =  0.35 CPU)
Result: FAIL
Failed 1/6 test programs. 0/17 subtests failed.
make: **\* [test_dynamic] Error 255

**Comment by jcpetkovich** [comment]
I'm sorry but I can't reproduce this issue. Please give me more details about your environment, and the full output of the install from start to finish.

**Comment by n00shie** [comment]
I am on Mac OS X, should be the standard perl environment that comes with the system. 

Note that I don't have problems installing the tool, I just ignored the make test output and continued with the instructions.

Here is the full output:

n00shie@Macintosh ~/Code/UW/school-projects/cs350/quiz_questions (master●)$ git clone git@github.com:jcpetkovich/App-QuestionValidator.git  [ruby-1.9.3-p194]
Cloning into 'App-QuestionValidator'...
remote: Counting objects: 106, done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 106 (delta 46), reused 106 (delta 46)
Receiving objects: 100% (106/106), 28.17 KiB, done.
Resolving deltas: 100% (46/46), done.

n00shie@Macintosh ~/Code/UW/school-projects/cs350/quiz_questions (master●)$ cd App-QuestionValidator                                        [ruby-1.9.3-p194]

n00shie@Macintosh ~/Code/UW/school-projects/cs350/quiz_questions/App-QuestionValidator (master)$ ls                                         [ruby-1.9.3-p194]
Changes            MANIFEST           Makefile.PL        README.markdown    lib                question-validator t

n00shie@Macintosh ~/Code/UW/school-projects/cs350/quiz_questions/App-QuestionValidator (master)$ cpan App-QuestionValidator                 [ruby-1.9.3-p194]
Going to read '/Users/n00shie/.cpan/Metadata'
  Database was generated on Sat, 12 Jan 2013 17:41:03 GMT
Warning: Cannot install App-QuestionValidator, don't know what it is.
Try the command

```
i /App-QuestionValidator/
```

to find objects with matching identifiers.

n00shie@Macintosh ~/Code/UW/school-projects/cs350/quiz_questions/App-QuestionValidator (master)$ perl Makefile.PL                           [ruby-1.9.3-p194]
Checking if your kit is complete...
Looks good
Writing Makefile for App::QuestionValidator

n00shie@Macintosh ~/Code/UW/school-projects/cs350/quiz_questions/App-QuestionValidator (master)$ make                                       [ruby-1.9.3-p194]
cp lib/App/QuestionValidator.pm blib/lib/App/QuestionValidator.pm
cp question-validator blib/script/question-validator
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/question-validator
Manifying blib/man1/question-validator.1
Manifying blib/man3/App::QuestionValidator.3pm

n00shie@Macintosh ~/Code/UW/school-projects/cs350/quiz_questions/App-QuestionValidator (master)$ make test                                  [ruby-1.9.3-p194]
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ....... 1/? # Testing App::QuestionValidator 0.01, Perl 5.012004, /usr/bin/perl
t/00-load.t ....... ok  
t/invalid.t ....... # Looks like your test exited with 25 before it could output anything.
t/invalid.t ....... Dubious, test returned 25 (wstat 6400, 0x1900)
Failed 14/14 subtests 
t/manifest.t ...... skipped: Author tests not required for installation
t/pod-coverage.t .. skipped: Test::Pod::Coverage 1.08 required for testing POD coverage
t/pod.t ........... ok  
t/valid.t ......... ok     

Test Summary Report

---

t/invalid.t     (Wstat: 6400 Tests: 0 Failed: 0)
  Non-zero exit status: 25
  Parse errors: Bad plan.  You planned 14 tests but ran 0.
Files=6, Tests=17,  0 wallclock secs ( 0.04 usr  0.02 sys +  0.25 cusr  0.04 csys =  0.35 CPU)
Result: FAIL
Failed 1/6 test programs. 0/17 subtests failed.
make: **\* [test_dynamic] Error 255

n00shie@Macintosh ~/Code/UW/school-projects/cs350/quiz_questions/App-QuestionValidator (master●)$ sudo make install                         [ruby-1.9.3-p194]
Password:
Installing /Library/Perl/5.12/App/QuestionValidator.pm
Installing /usr/local/share/man/man1/question-validator.1
Installing /usr/local/share/man/man3/App::QuestionValidator.3pm
Installing /usr/local/bin/question-validator
Appending installation info to /Library/Perl/Updates/5.12.4/darwin-thread-multi-2level/perllocal.pod

**Comment by jcpetkovich** [comment]
I'm curious, does the script appear to run without issue? Or does it complain of missing modules? I've also pushed a version that will have slightly noisier tests, could you please run that and share the output?

**Comment by jcpetkovich** [comment]
I've pushed a few changes to use the old api of perl 5.12's IO::File class instead of 5.16's. Could you check to see if this resolves your issue?

**Comment by n00shie** [comment]
Not removing the old installation, and just re-cloning the repo and installing again yields an additional error:

```
t/invalid.t ....... Can't locate object method "new" via package "IO::File" at t/invalid.t line 15.
```

Also this seems to indicate it's using perl 5.12 right?

```
t/00-load.t ....... 1/? # Testing App::QuestionValidator 0.01, Perl 5.012004, /usr/bin/perl
```

Sorry I have zero experience with Perl, this could easily just be my silly environment, since no one else is complaining. The actual validator seems to run fine with no problems.

For reference here is the full output of running make test:

```
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ....... 1/? # Testing App::QuestionValidator 0.01, Perl 5.012004, /usr/bin/perl
t/00-load.t ....... ok   
t/invalid.t ....... Can't locate object method "new" via package "IO::File" at t/invalid.t line 15.
# Looks like your test exited with 255 before it could output anything.
t/invalid.t ....... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 16/16 subtests 
t/manifest.t ...... skipped: Author tests not required for installation
t/pod-coverage.t .. skipped: Test::Pod::Coverage 1.08 required for testing POD coverage
t/pod.t ........... ok   
t/valid.t ......... ok     

Test Summary Report
-------------------
t/invalid.t     (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 16 tests but ran 0.
Files=6, Tests=19,  0 wallclock secs ( 0.04 usr  0.03 sys +  0.25 cusr  0.04 csys =  0.36 CPU)
Result: FAIL
Failed 1/6 test programs. 0/19 subtests failed.
make: *** [test_dynamic] Error 255
```

**Comment by jcpetkovich** [comment]
5.012004 is indeed perl 5.12

Excellent, I found the error, at least I hope I did.

IO::File is not imported by default in 5.12, if I remember it was still new at the time. It's been a while since I've used 5.12, sorry about that.

Try the most recent push please.

**Comment by avishesh** [comment]
This is what i got when i tried to set up the newest version today in my Mac OS mountain lion:

Going to read '/Users/Avishesh/.cpan/Metadata'
  Database was generated on Sun, 20 Jan 2013 02:06:30 GMT
You are visiting the local directory
  '/Users/Avishesh/Desktop/App-QuestionValidator/.'
  without lock, take care that concurrent processes do not do likewise.
Running make for /Users/Avishesh/Desktop/App-QuestionValidator/.

  CPAN.pm: Going to build /Users/Avishesh/Desktop/App-QuestionValidator/.

Checking if your kit is complete...
Looks good
Writing Makefile for App::QuestionValidator
cp lib/App/QuestionValidator.pm blib/lib/App/QuestionValidator.pm
cp question-validator blib/script/question-validator
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/question-validator
Manifying blib/man1/question-validator.1
Manifying blib/man3/App::QuestionValidator.3pm
  /Users/Avishesh/Desktop/App-QuestionValidator/.
  /usr/bin/make -- OK
Directory '/Users/Avishesh/Desktop/App-QuestionValidator/.' not below /Users/Avishesh/.cpan/build, will not store persistent state
Running make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ....... 1/? # Testing App::QuestionValidator 0.02, Perl 5.012004, /usr/bin/perl
t/00-load.t ....... ok  
t/invalid.t ....... 1/16 question-validator:1:0: error: Question set as something other than MC.
question-validator:10:0: error: Exactly four options are required.
question-validator:9:0: error: Exactly one fully correct answer is required.
question-validator:10:0: error: Exactly one fully correct answer is required.
Use of uninitialized value in numeric ge (>=) at blib/lib/App/QuestionValidator.pm line 584, <GEN0> line 12.
question-validator:8:0: error: Only up to two options may be worth more than or equal to 50.
question-validator:9:0: error: Only up to two options may be worth more than or equal to 50.
question-validator:10:0: error: Only up to two options may be worth more than or equal to 50.
question-validator:1:0: error: The type row should have the tag "NewQuestion" and should be of size 3
question-validator:2:0: error: The title row should have the tag "Title" and should be of size 3
question-validator:6:0: error: Each option should have 5 columns.
question-validator:6:0: error: Each option's fourth column should be empty (see example in manual), it's a placeholder for learn's stuff, don't ask me why they did it this way.
question-validator:7:0: error: Each option's fourth column should be empty (see example in manual), it's a placeholder for learn's stuff, don't ask me why they did it this way.
question-validator:8:0: error: Each option's fourth column should be empty (see example in manual), it's a placeholder for learn's stuff, don't ask me why they did it this way.
question-validator:9:0: error: Each option's fourth column should be empty (see example in manual), it's a placeholder for learn's stuff, don't ask me why they did it this way.
question-validator:10:0: error: Each option's fourth column should be empty (see example in manual), it's a placeholder for learn's stuff, don't ask me why they did it this way.
question-validator:6:0: error: Feedback required for every option.
question-validator:7:0: error: Feedback required for every option.
question-validator:8:0: error: Feedback required for every option.
question-validator:9:0: error: Feedback required for every option.
question-validator:10:0: error: Feedback required for every option.
question-validator:11:0: error: Each option row should start with "Option".
question-validator:5:0: error: The question row should start with "QuestionText" and have 3 columns.
question-validator:5:0: note: I suggest putting a newline at the very beginning of your question text, and also at the very end. If you do not put newlines at the beginning and the end of the string, learn will not treat your newlines literally, and will format your question as it sees fit.
question-validator:12:0: error: Question feedback rows should start with "Feedback" and have 6 columns.
question-validator:12:0: note: I suggest putting a newline at the very beginning of your feedback text, and also at the very end. If you do not put newlines at the beginning and the end of the string, learn will not treat your newlines literally, and will format your feedback as it sees fit.
t/invalid.t ....... ok  
t/manifest.t ...... skipped: Author tests not required for installation
t/pod-coverage.t .. skipped: Test::Pod::Coverage 1.08 required for testing POD coverage
t/pod.t ........... ok  
t/valid.t ......... ok  
All tests successful.
Files=6, Tests=35,  1 wallclock secs ( 0.04 usr  0.03 sys +  0.27 cusr  0.06 csys =  0.40 CPU)
Result: PASS
  /Users/Avishesh/Desktop/App-QuestionValidator/.
  /usr/bin/make test -- OK
Running make install
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Can't create '/Library/Perl/5.12/App'
mkdir /Library/Perl/5.12/App: Permission denied at /System/Library/Perl/5.12/ExtUtils/Install.pm line 494

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 at -e line 1
make: **\* [pure_site_install] Error 13
  /Users/Avishesh/Desktop/App-QuestionValidator/.
  /usr/bin/make install  -- NOT OK

**Comment by jcpetkovich** [comment]
This looks like it's due to a lack of permissions rather than a problem with cpan or the module. If you wish to install it without root permissions I suggest using perl's [local::lib](https://metacpan.org/module/local::lib). You should be able to find installation instructions there for a variety of scenarios, when it's all said and done you will have your own user level set of perl libs in ~/perl5 (or wherever else you define) that you can delete entirely on a whim. With that directory in place, If you execute cpan with only regular user level permissions it will install to your user perl library directory instead of the system wide one.

**Comment by n00shie** [comment]
Yep, it's just the outdated perl on my mac. And you are right, sudo solves the rest of the problems.

**Comment by jcpetkovich** [comment]
Great! Thanks for helping me test it on Mac OS.
